### ISSUE TITLE
this is not an issue

### ISSUE THREAD

**Issue by jrence** [aw3rque/np-doors#1]
how this np-doors working which job can pull this?? on esx  framework?

or can you point me out how this works on certain job to unlock a door and lock

**Comment by aw3rque** [comment]
hey,

    if (ESX.PlayerData.job.name == "jrence" or hasSteamIdKeys) and (curClosestNum == 1or curClosestNum == 2) then
        return false
    end

**I'm just giving jobs as an example**

this code shows that job named jrence (1stand 2nd) can open doors.
